### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by nikoudel** [tkellogg/Jump-Location#70]
The patient appears to be more dead than alive.

For my needs the following function placed in the PowerShell profile script is enough:

```PowerShell
function j {
    Param(
        [Parameter(Mandatory=$true, Position=0)][string]$locationName
    )

    $locations = @{
        "one" = "C:\path\to\location-one"
        "two" = "C:\path\to\location-two"
        "three" = "C:\path\to\location-three"
    }

    if ($locations.ContainsKey($locationName))
    {
        Set-Location $locations.$locationName
    }
    else
    {
        Write-Host -ForegroundColor Red "Unknown location: $locationName"
    }
}
```

**Comment by vors** [comment]
Another alternative https://github.com/vors/ZLocation

**Comment by vors** [comment]
To answer your question

> Is this repository dead?

The module is published and works for a lot of people but no active development is planned at the moment.

**Comment by nikoudel** [comment]
> The module is published and works for a lot of people but no active development is planned at the moment.

It worked fine for me too for a while until I've got some issues and went to the project page to file a bug report only to discover the last development took place in 2014.

If a project's support is over (i.e. it's dead) it's a good practice to mention that on the main page, especially if there is an alternative which is still maintained. Btw, thanks for the link!
